### ISSUE TITLE
Update parser so all paths may contain CGI/query elements

### ISSUE THREAD

**Issue by paulmillar** [dCache/xrootd4j#23]
As clarified in xrootd/xrootd#850, all paths in any xrootd request may contain CGI elements (a query string).

Currently all operations, (except kXR_open and kXR_mv) treat all paths as if they have no CGI elements, as the xrootd protocol spec currently doesn't mention this behaviour.

This results in clients potentially sending valid paths to xroot4j that then fail.

To fix this, all operations should be examined and any paths should remove the query string argument.  Additional getter methods should be added to provide access to these optional elements.

**Comment by alrossi** [comment]
Will have to review the protocol to see what other operations include path information (besides the obvious ones).


Do we even support things like kXR_putfile and kXR_getfile ? ... I don't remember.


I guess I'm the logical one to take care of this.


Al

________________________________________________
Albert L. Rossi
Application Developer & Systems Analyst III
Scientific Computing Division, Data Movement Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023


________________________________

**Comment by paulmillar** [comment]
Yes, that's why I created this issue, we need to go through all operations and identify which ones have a path and make sure we strip off any query-part.

I think we should also take this advantage of this opportunity to add unit tests for this.  See `StatRequestTest` for one possible way of achieving this.

**Comment by alrossi** [comment]
Let me clarify something here.

First, there are already a set of requests:

DirListRequest
LocateRequest
MkDirRequest
OpenRequest
RmDirRequest
RmRequest
StatRequest

which sublcass PathRequest.   When the message buffer is parsed in their constructors, it is already split on a the potential opaque delimiter ('?').

So we are already supporting queries on those requests.

The case of mv seems to be special, because two paths are involved.

The code for the the MvRequest thus is a one-off.

The issue seems to be in the assumption that only the target path can have an opaque (query) string.


```
public MvRequest(ByteBuf buffer) {
        super(buffer, kXR_mv);

        int dlen = buffer.getInt(20);
        int end = 24 + dlen;

        int psep = buffer.indexOf(24, end, (byte)0x20);
        int osep = buffer.indexOf(psep, end, (byte)0x3f);

        if (psep == -1) {
            throw new IllegalArgumentException("kXR_mv needs two paths!");
        }

        if (osep > -1) {
            sourcePath = buffer.toString(24,
                                          psep - 24,
                                          US_ASCII);
            targetPath = buffer.toString(psep+1,
                                          osep - (psep + 1),
                                          US_ASCII);
            opaque = buffer.toString(osep + 1,
                                      end - (osep + 1),
                                      US_ASCII);
        } else {
            sourcePath = buffer.toString(24,
                                          psep - 24,
                                          US_ASCII);
            targetPath = buffer.toString(psep+1,
                                          end - (psep + 1),
                                          US_ASCII);
            opaque = null;
        }
    }
```

I don't believe we need, therefore, to fix a general problem, just this class.

**Comment by alrossi** [comment]
https://rb.dcache.org/r/11422/

needs more testing

I am not sure that xrdfs actually is sending the query part

**Comment by alrossi** [comment]
Testing complete, patch committed to master, with pull request for 3.3

https://github.com/dCache/xrootd4j/pull/27
