### ISSUE TITLE
Stack-traced logged by mistake

### ISSUE THREAD

**Issue by paulmillar** [dCache/xrootd4j#4]
In user-forum, we have reports like:

```
21 Aug 2017 10:17:47 (Xrootd-uct2-xrootd) [door:Xrootd-uct2-xrootd@uct2-xrootdDomain-1094:AAVXRPs0mFA] Error during decrypting/server-side key exchange: {}
javax.crypto.BadPaddingException: pad block corrupted
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source) ~[bcprov-jdk15on-1.50.jar:1.50.0]
	at javax.crypto.Cipher.doFinal(Cipher.java:2165) ~[na:1.8.0_91]
	at org.dcache.xrootd.plugins.authn.gsi.DHSession.decrypt(DHSession.java:200) ~[xrootd4j-gsi-3.2.2.jar:3.2.2]
	at org.dcache.xrootd.plugins.authn.gsi.GSIAuthenticationHandler.handleCertStep(GSIAuthenticationHandler.java:302) [xrootd4j-gsi-3.2.2.jar:3.2.2]
```

Note how the log message is `Error during decrypting/server-side key exchange: {}`.  This points to a simple mistake where the desire was to log the exception's message, but a stack-trace is logged instead.

**Comment by DmitryLitvintsev** [comment]
https://github.com/dCache/xrootd4j/pull/5

**Comment by alrossi** [comment]
Aside from the logging error, has anyone gotten to the bottom of this?

I'm now encountering this more frequently when I do something like the following:

for i in {1..30}
do 
     xrdcopy --tpc only root://fndcatemp1.fnal.gov:1095//pnfs/fs/usr/test/arossi/volatile/nonzero root://fndcatemp2.fnal.gov:1094//data/xrootdfs/nonzero-from-door-${i}-`date | tr ' ' '-'` & 
done

that is, when dCache acts as the source server to a SLAC server as destination in third-party copy

This will also occur, obviously, in a dCache to dCache third-party tranfer.

I have been looking at what's on the web.  Not really too clear whether this is a problem with the way the secret key is composed (BC does not use strings, but a byte array from a big int, so this doesn't seem to be relevant), or whether we should just turn off padding for DH encryption (note that it is the DHSession.decrypt method in the stack trace above which causes the exception).  

I tried updating SERVER_SYNC_CIPHER_MODE = "AES/CBC/PKCS7Padding" (from AES/CBC/PKCS5Padding".  At first this seemed to help, but then it started cropping up again.

.... to be continued ...

**Comment by alrossi** [comment]
This looks like it fixes it:

https://rb.dcache.org/r/11047/

**Comment by paulmillar** [comment]
Note that this problem has also been reported in RT at least once.  Jürgen is currently investigating the RT ticket.

The problem appears to be "random" -- some transfers appear to be affected while others are not.  (I believe) the same transfer when repeated then succeeds.

I believe what is happening is some aspect of the session is different for different transfers.  This could be the session secret (as established through the DH process) or it could be something else.

**Comment by paulmillar** [comment]
Ticket: http://rt.dcache.org/Ticket/Display.html?id=9129
Ticket: http://rt.dcache.org/Ticket/Display.html?id=9218
Ticket: http://rt.dcache.org/Ticket/Display.html?id=9444

**Comment by paulmillar** [comment]
I suggest this ticket is *specifically* about the stack-trace.  The stack-trace is because the dCache logging is broken.

Please do not try to fix the underlying problem with this ticket -- that still needs to be fixed, but we can get rid of the stack-trace since this is a trivial 2-minute patch.

**Comment by alrossi** [comment]
On the cert step, the main bucket is encrypted with the DH session key.  

Hence the issue may very well have to do with the double decryption.  First, the whole bucket is decrypted using the secret key.  Then the signed challenge in the main bucket is decrypted using the host cert.   The failure is always on the second decryption.

**Comment by alrossi** [comment]
I've opened https://github.com/dCache/xrootd4j/issues/6 for the underlying issue.

Note that the stack trace has been repaired (see Dmitry's comment above --> #5).

This issue should be closed.
