### ISSUE TITLE
Error during decrypting/server-side key exchange: pad block corrupted

### ISSUE THREAD

**Issue by alrossi** [dCache/xrootd4j#6]
Same as

Ticket: http://rt.dcache.org/Ticket/Display.html?id=9129
Ticket: http://rt.dcache.org/Ticket/Display.html?id=9218
Ticket: http://rt.dcache.org/Ticket/Display.html?id=9444

Opening new issue.

**Comment by alrossi** [comment]
Note that the signed challenge is doubly encrypted; could the RSA encryption of the challenge -- not the challenge string itself, as my first attempt thought -- be causing the issue for the decryption of the entire bucket using the DH secret key?.

**Comment by alrossi** [comment]
I have another theory about this, and I will post another patch.

I should have thought of this earlier.  When implementing client-side DH, where the client has to accept the server's parameters (in this case, SLAC's), I found that while the BouncyCastleLibrary claims that if L = 0, it will be set automatically to the bit length of P, leaving L = 0 when you do finalize often provokes a similar failure.

The suggested change in this case is always to set L explicitly.  When the client sends back P, G, L, the latter is as far as I can tell always 0.  Setting it to P.bitLength is what I suggest.

I've done this, and since deploying the patch, I have not been able to reproduce the BadPaddingException.

That is the problem, though.  Because it is hard to ascertain the conditions under which this happens and thus hard to reproduce, we still risk this being a false negative.

But I will post the patch anyway.  At least the L parameter seems possibly to relate more directly to the issue than the string encoding.

**Comment by alrossi** [comment]
https://rb.dcache.org/r/11048/

**Comment by alrossi** [comment]
As I feared.  False negative.  This morning, retrying, I got one failure
17 Jul 2018 07:16:59 (Xrootd0-fndcatemp1) [door:Xrootd0-fndcatemp1@xrootd-fndcatemp1Domain:AAVxMOxD9dk] Error during decrypting/server-side key exchange: pad block corrupted

This is really aleatoric.

I don't suppose this patch does any harm, but it doesn't solve the problem.

**Comment by alrossi** [comment]
I can also state that the corruption does not appear to have any relation to parallelism (i.e., it is not the product, evidently, of bad synchronization in the dCache door), because I just got one failure during a run of 50 consecutive (i.e., serial) transfers as well.

**Comment by alrossi** [comment]
Here is an update on my findings.

I have recompiled the bouncy castle jars with debugging output in crucial places.  This is what I see:

The error comes from an occasional bad padding value on the last byte of the 16-byte block.

The bouncy castle encoding assumes the following:

public int addPadding(
    byte[]  in,
    int     inOff)
{
    byte code = (byte)(in.length - inOff);
  
    while (inOff < in.length)
    {
        in[inOff] = code;
        inOff++;
    }

    return code;
}

in other words, all excess bytes are padded with the length - offset value.

Similarly, on decryption, it computes the padding count from the last byte in the input block.

public int padCount(byte[] in)
    throws InvalidCipherTextException
{
    int count = in[in.length - 1] & 0xff;
    if (count > in.length || count == 0)
    {
        throw new InvalidCipherTextException("pad block corrupted");
    }
    
    for (int i = 1; i <= count; i++)
    {
        if (in[in.length - i] != count)
        {
            throw new InvalidCipherTextException("pad block corrupted");
        }
    }

    return count;
}

The error we are seeing is consistently from the first condition, before we even reach the for-loop.

It looks like this:

padCount: input length: 16, last byte: 17, count: 17
count greater than input length (or = 0)
all bytes: zfG49Jb0zdW0c6etvNlEEQ==
...

padCount: input length: 16, last byte: -5, count: 251
count greater than input length (or = 0)
all bytes: kHy3xOB2O0kCeCzz1iO4+w==

...

padCount: input length: 16, last byte: -46, count: 210
count greater than input length (or = 0)
all bytes: FJkeq/kP7bqw+mX+TskC0g==

I am nearly positive this is always the xrdcp client, because I did this test door to door, and the tpc client on the pool consistently produces a padding value of 7:

adding padding: input length: 16, offset: 9, padding code: 7
adding padding: input length: 16, offset: 9, padding code: 7
adding padding: input length: 16, offset: 9, padding code: 7
...
etc.

which shows up in the source door log the same way:

padCount: input length: 16, last byte: 7, count: 7
padCount: input length: 16, last byte: 7, count: 7
padCount: input length: 16, last byte: 7, count: 7

Whereas the vast majority of the time, the xrdcp client has six bytes left:

padCount: input length: 16, last byte: 6, count: 6
padCount: input length: 16, last byte: 6, count: 6
padCount: input length: 16, last byte: 6, count: 6

...

Why this is happening?  Not sure yet.  It could be the fact that in bouncy castle 1.50 (which we are using), PKCS5Padding is replaced by PKCS7Padding.  If the xrdcp library continues to use PKCS5Padding, that might be the cause (in other words, the padding methods above done't work with what xrdcp sends us).

I have not yet been able to ascertain what padding scheme is indeed used there.

I remember we had issues moving off of bc 1.49 some time ago.  Maybe this is another such issue?

**Comment by alrossi** [comment]
No, I don't think the problem is PKCS5 vs 7.

https://crypto.stackexchange.com/questions/9043/what-is-the-difference-between-pkcs5-padding-and-pkcs7-padding

5 is just a subset of 7, so if dCache is getting 8-byte blocks it should work.

Something else is wrong.

**Comment by alrossi** [comment]
And it is not the actual size of the encrypted buffer that is the problem (I was looking possibly for a bad delimiter which might confuse Netty's readableBytes count).

19 Jul 2018 10:42:27 (Xrootd0-fndcatemp1) [door:Xrootd0-fndcatemp1@xrootd-fndcatemp1Domain:AAVxXAa7S0g] Length of input: 2944, % blocksize = 0.
19 Jul 2018 10:42:27 (Xrootd0-fndcatemp1) [door:Xrootd0-fndcatemp1@xrootd-fndcatemp1Domain:AAVxXAa7LAk] Length of input: 2944, % blocksize = 0.
19 Jul 2018 10:42:27 (Xrootd0-fndcatemp1) [door:Xrootd0-fndcatemp1@xrootd-fndcatemp1Domain:AAVxXAa7LAk] Error during decrypting/server-side key exchange: pad block corrupted
19 Jul 2018 10:42:27 (Xrootd0-fndcatemp1) [door:Xrootd0-fndcatemp1@xrootd-fndcatemp1Domain:AAVxXAa7R2A] Length of input: 2944, % blocksize = 0.

**Comment by alrossi** [comment]
One last observation for the day.  I tried tcp dump on the three endpoints, managed to produce an error and identify the packets (I think) which correspond to it.  Except for the tcp headers, they look identical on both ends (hex-dump-wise).   The error was from the third-party xrdcp client used by the SLAC server.  I can't tell yet whether the bad value is present in the HEX dump, or whether it is an artifact of netty/dCache.   I'll keep investigating.

**Comment by alrossi** [comment]
CONFIRMED:

hex dumps for the encrypted buffer for (a) tcp outgoing (SLAC), (b) tcp incoming (dCache DOOR), and (c) JVM/Netty parsed, on error (where last byte value > block length) are identical.

Here's the mysterious part.

1.   In all three, the number of blocks is consistent:  184 X 16 bytes = 2944 bytes.
2.   The last byte of the sequence in all three = 20 in hex, which means 32 decimal.  But ...
3.   The error related to this dump: 

20 Jul 2018 08:23:54 (Xrootd0-fndcatemp1) [door:Xrootd0-fndcatemp1@xrootd-fndcatemp1Domain:AAVxbjUYjUA] Length of input: 2944, % blocksize = 0.
padCount: input length: 16, last byte: 50, count: 50
count greater than input length (or = 0)

50 in decimal = 32 in hex.

in the dump, there are numerous bytes with hex value 32, none of which are the 16th byte of the block.

However, if we doubly translate the last byte from hex to decimal:

20 (hex) -> 32 (dec)
32 (hex) -> 50 (dec) ...

That may be a coincidence, but I cannot for the life of me see where the last byte value of the pad block corresponds to anything in the dumps.

**Comment by alrossi** [comment]
I think I'm losing my mind.  Of course 20 won't correspond.  It's the encrypted value. Duh.

So there must be something asymmetrical about the encryption->decryption for certain values which screws up the padding.

**Comment by DmitryLitvintsev** [comment]
So you have come a full circle here. 

I should note that I believe these padding issues started to appear in version 2.13. Might be coincidental w/ different version of xrdcp so who knows.

**Comment by alrossi** [comment]
Working on a test or set of tests where I can control encryption/decryption parameters on DH symmetric key, to be able to run many encrypt/decrypt sequences and capture the failures.

**Comment by alrossi** [comment]
https://github.com/alrossi/dcache-server/tree/fix/xrootd4j/dh-padding-issue

The two test cases:

(a) each client-server connection has its own DH session object.
(b) the server reuses the same DH session object for every client.

Running about 300 clients, it is clear that (a) works fine, but (b) sporadically produces the pad block corrupted error in question.

(b) Is clearly the wrong thing to do, but it shows that something like this must be happening, even though the way the server is written, each new child channel gets a new GSIAuthenticationHandler, and thus also a new DHSession object; that is, the server is actually implemented like (a).

Can an old handler somehow get erroneously recycled to a new client connection?

**Comment by alrossi** [comment]
The idea that a race is behind this error has been hard to confirm.

I have tracked object hashes as deep as the BouncyCastle AES engine, and objects are used uniquely as they should be.  So bad synchronization does not seem to be at issue.

My only thoughts left currently is that somehow the AESFast algorithm that is used is susceptible to sporadic errors such that it encrypts OK but cannot decrypt.   In other words, a BC implementation issue.  I say this because obviously the SLAC server, which uses the openssl C++ library, does not experience this problem.

**Comment by alrossi** [comment]
Another data point:
if you execute

```
for i in {1..1000}
do
  xrdcopy root://fndcatemp1.fnal.gov:1095//pnfs/fs/usr/test/arossi/volatile/data_10mb /data2/arossi/test-${i}-`date | tr ' ' '-'`
done
```
that is, normal two-party copies, purely sequentially (and there is no other activity on the door), you can provoke the error.   With this 10Mb file, I saw 10/1000 failures.

**Comment by alrossi** [comment]
With an 80 MB file, the same test produced 4/1000 failures.

**Comment by alrossi** [comment]
Here is an example of what I mentioned previously.  

Notice that this is a purely sequential test, 10 mb files in 2-party copy with 1 second interval between requests.

Notice that the authentication handler is unique to the operation which fails, as is the DH Session object.

[xrootd-fndcatemp1Domain.log](https://github.com/dCache/xrootd4j/files/2254277/xrootd-fndcatemp1Domain.log)

**Comment by alrossi** [comment]
More detail.  BC objects are also seen to be unique:

[xrootd-fndcatemp1Domain.txt](https://github.com/dCache/xrootd4j/files/2254361/xrootd-fndcatemp1Domain.txt)

**Comment by alrossi** [comment]
Here's another example.

If we do the same test as above (single, serialized transfer), but third-party from dCache door to door, the failures seen always seem to be associated with stream 0, that is, the SLAC client.  Sometimes in logging in to the source, sometimes the destination door.

The file contains a dump of the encrypted buffer and secret key for each door/server-side failure (three examples).  Below that, for comparison, is output from the dCache TPC client (which did not fail).

Nothing pops out in terms for differences that I can discern.
[examples.txt](https://github.com/dCache/xrootd4j/files/2258097/examples.txt)

**Comment by alrossi** [comment]
Thanks, Dmitry.  If the problem is still open when I return, I can see if dropping the BC library dependency back to the previous one would still work on 4.2.  I can also inspect for differences in the algorithm implementation.

**Comment by DmitryLitvintsev** [comment]
I have been running xrdcp in a loop against our production ( dcache 2.16) and CMS instance ( dcache 2.13) 

I am seeing this issue in 0.5% of transfers against production

I am NOT seeing this issue when transferring from CMS (good statistics ~ 50K transfers) 

Major diff I see between 2.13 and 2.16 is bouncycastle version and switch to CANL

bouncycastle switch is patch c68b78162c6a96f8d7bd5f082a7bf2d09ed8785b 

2.16 uses 3.1.1 xrootd4j
2.13 uses 2.1.5 xrootd4j 

It least we may find a point at which this got broken

**Comment by DmitryLitvintsev** [comment]
> Thanks, Dmitry. If the problem is still open when I return, I can see if dropping the BC library dependency back to the previous one would still work on 4.2. I can also inspect for differences in the algorithm implementation.

I am afraid this is not quite possible. I think b/c of CANL. I think we need to find a breaking commit and see what we can do. Worst case we can catch a bug in bouncycastle. Best case we can mitigate.

**Comment by alrossi** [comment]
Ah, yes, right.  Rings a bell now.  OK, if you or someone else doesn't get to this over the next 5 days, I'll do the bisect when I get back.

**Comment by rptaylor** [comment]
This started happening on our T2 SE on Oct 31, when we upgraded dCache nodes.

The particular updates on the xrootd door were:

Java upgraded from Oracle's jdk1.8.0_151 x86_64 to java-1.8.0-openjdk-1.8.0.181-3.b13.el6_10.x86_64

dCache upgraded from 2.13.61 to 3.2.37

Full yum log is here: https://cernbox.cern.ch/index.php/s/JKOyzwhUpi57iHR

There were no updates to the clients in our cluster at this time as far as I know.

**Comment by DmitryLitvintsev** [comment]
Hi Ryan., 

This issue is fixed in dCache release 4.2.15. 

See release notes: https://www.dcache.org/downloads/1.9/release-notes-4.2.shtml#15

I highly recommend you to upgrade to the latest 4.2 release (4.2.16). 

3.2 -> 4.2 upgrade must be trivial (e.g. no DB changes minimal config differences). 

If for some reason upgrade of your whole system is not feasible, you can upgrade only on the node running xrootd door(s). Golden releases are backward compatible (not that you should not test it carefully on a test system). 

Dmitry

**Comment by rptaylor** [comment]
Hi Dmitry,

Okay thanks, good to know. The 4.2 upgrade may be relatively easy, nevertheless, v3.2 is a current golden release so it would be nice to have the fix backported. I will look into potentially doing yet another upgrade or possibly switching to a different data transfer protocol.

Thanks!

**Comment by DmitryLitvintsev** [comment]
yeah. We have discussed it. The rationale of having it in 4.2 vs 3.2 was to minimize the risk to existing golden release (the fix involves bouncycastle and dependent libraries upgrades which was deemed risky). Alternative to upgrade to 4.2 could be us providing you with a custom 3.2 release where this issue is fixed and you run it and report that no other issues are seen (I am pretty much confident about that). In this case we can say that the fix has been "field tested" and we can merge the fix to 3.2 branch 

Dmitry

**Comment by alrossi** [comment]
The encryption limit/offset error is now handled

see https://rb.dcache.org/r/11454/
see https://github.com/dCache/xrootd4j/pull/28

Thus a move by SLAC to the padded SSL method is not immediately necessary.

**Comment by alrossi** [comment]
With xrootd 4.9, and signed hash verification turned on, decryption on the first signed hash is consistently failing:

```
13 Mar 2019 15:15:31 (Xrootd1-fndcatemp1) [NIC auto-discovery] Adding fndcatemp1.fnal.gov/131.225.240.89
javax.crypto.BadPaddingException: pad block corrupted
        at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(Unknown Source)
        at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)
        at javax.crypto.Cipher.doFinal(Cipher.java:2165)
        at org.dcache.xrootd.plugins.authn.gsi.DHSession.translate(DHSession.java:367)
        at org.dcache.xrootd.plugins.authn.gsi.DHSession.decrypt(DHSession.java:206)
        at org.dcache.xrootd.plugins.authn.gsi.DHBufferHandler.decrypt(DHBufferHandler.java:63)
        at org.dcache.xrootd.protocol.messages.SigverRequest.decrypt(SigverRequest.java:97)
        at org.dcache.xrootd.core.XrootdSigverDecoder.verifySignedHash(XrootdSigverDecoder.java:205)
        at org.dcache.xrootd.core.XrootdSigverDecoder.decode(XrootdSigverDecoder.java:117)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.dcache.xrootd.door.ConnectionTracker.channelRead(ConnectionTracker.java:68)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.dcache.xrootd.door.NettyXrootdServer$SessionHandler.channelRead(NettyXrootdServer.java:344)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at org.dcache.util.CDCThreadFactory.lambda$newThread$0(CDCThreadFactory.java:50)
        at java.lang.Thread.run(Thread.java:745)
```
the code in BC
```
public int doFinal(byte[] out, int outOff) throws IllegalStateException, BadPaddingException
{
    try
    {
        return cipher.doFinal(out, outOff);
    }
    catch (InvalidCipherTextException e)
    {
        throw new BadPaddingException(e.getMessage());
    }
}
```

I am wondering if we need to switch to NoPadding for signed hash.

**Comment by DmitryLitvintsev** [comment]
Somehow I think this needs to be new issue Called "xrootdcp version 4.9 does not work with xrootd4j"

**Comment by DmitryLitvintsev** [comment]
https://github.com/dCache/xrootd4j/blob/3050c5fdea3aee04c96d00b383567f8472050100/xrootd4j-gsi/src/main/java/org/dcache/xrootd/plugins/authn/gsi/DHSession.java#L246

Al, look at above code. 

line 246. Then encoded is defined, then on linen 273 it is not used by created again as argument to SecretKeySpec constructor. 

Not understanding. At the very least it is not efficient.

**Comment by alrossi** [comment]
Yes, I saw that today and changed it.  I think this was an artifact of having manipulated the code so many times.  I don't think it has an impact on this issue, though; it's just inefficient.


-Al


________________________________________________
Albert L. Rossi
Application Developer & Systems Analyst III
Scientific Computing Division, Data Movement Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023


________________________________

**Comment by DmitryLitvintsev** [comment]
In case if DECRYPT yes, just inefficient. In case of ENCRYPT it is wrong. The whole block where you massage 'encoded' is made noop.

**Comment by DmitryLitvintsev** [comment]
(did I ack this ? )

**Comment by alrossi** [comment]
Yes, that is what I meant by "on this issue", since it is a matter of decrypt here.  It is clearly erroneous in terms of what it is trying to achieve with encrypt.

Opening new issue.
